CREATE TABLE IF NOT EXISTS "cart_items" (
  "id" SERIAL,
  "quantity" INTEGER,
  "user_id" INTEGER REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE CASCADE,
  "product_id" INTEGER REFERENCES "products" ("id") ON DELETE NO ACTION ON UPDATE CASCADE,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);